### ISSUE TITLE
Tweet automatique nouvel article

### ISSUE THREAD

**Issue by Shalf** [antistatique/antistatique-2012#27]
- Supprimer cette fonction, qui empêche le formatage spécifique à twitter (notamment les #, un bref descriptif qui doit être différent du simple titre pour être efficace)
- Trouver une alternative générant un lien goo.gl / bit.ly trackable néanmoins (proposition : creuser les possibilités via Buffer)

**Comment by gido** [comment]
Il m'a fallu un moment pour remonter la piste et trouver la source de la publication automatique: il s'agit de Feedburner!

J'ai désactiver le module "socialize" de Feedburner.
Je suis pour supprimer Feedburner de manière générale, on lit pas les analytics (en tout cas pas moi) et on a que 15 abonnés RSS de toute façon. On risque juste de flingué la config de certain lecteur RSS...

**Comment by Shalf** [comment]
Merci Gilles. Je ferai une autre issue pour les alternatives url tracking.
