### ISSUE TITLE
Mettre contenu dans le wiki github

### ISSUE THREAD

**Issue by zufrieden** [antistatique/antistatique-2012#4]

**Comment by Shalf** [comment]
Toutes les v1 posées.
Je dois maintenant comparer aux maquettes de Vincent.

**Comment by Shalf** [comment]
Uchitomi à jour : coquilles corrigées et modifications / ajout à prendre en compte (notamment le testimonial client à la fin.

**Comment by Shalf** [comment]
RDR à jour : ajout BRIEF et SOLUTION pour remplacer les placeholders issus d'Uchitomi.

ATTENTION : le bloc d'icônes compétences et les descriptifs liés sont à vérifier (copié/collé Uchitomi dans la v1 du design)

**Comment by Shalf** [comment]
TW ok
