### ISSUE TITLE
Stop having a fixed top bar

### ISSUE THREAD

**Issue by gagarine** [antistatique/antistatique-2012#44]
This was a cool things in 2012 but I think it's useless and take screen space for nothings.

This is also a problem to have always this huge pink area than not always match with us screenchost.

So I'm for removing the fixed position on header.topbar .

**Comment by gagarine** [comment]
@zufrieden it's ok for you?

**Comment by zufrieden** [comment]
Ok for me.

**Comment by zufrieden** [comment]
fixed
