### ISSUE TITLE
Related content should be on the bottom

### ISSUE THREAD

**Issue by gagarine** [antistatique/antistatique-2012#45]
Those control for going to next a preview content have more sens at the bottom. I'm in fact more to change that for some kind of related content....

![screen shot 2014-04-26 at 17 49 09](https://cloud.githubusercontent.com/assets/164074/2809117/5210514e-cd5a-11e3-9dee-ee2450e5dd52.png)

@zufrieden what do you think?

**Comment by zufrieden** [comment]
yes. Normal behavior would be to treat this as a pagination system. At the bottom with : 

```
< Previous project                  |                   Next project >
```

Or even better

```
< Previous project                  |                   Back to the list                  |                   Next project >
```

Or even even better

```

< Previous project                  |                   Back to the list                  |                   Next project >
Suggested projects :       Project A                  |                   Project B                  |                   Project C
```

**Comment by zufrieden** [comment]
Fixed, on fera les suggestion de projet dans la version D8 ;-)
