### ISSUE TITLE
Media Queries for IE

### ISSUE THREAD

**Issue by gido** [antistatique/antistatique-2012#5]

**Comment by zufrieden** [comment]
Oups ... IE7

**Comment by zufrieden** [comment]
http://sht.tl/Iosp6

**Comment by zufrieden** [comment]
IE8 :-(
http://sht.tl/E4E3

**Comment by zufrieden** [comment]
mais sur IE8 c'est peut etre lié au script de @gido

**Comment by gagarine** [comment]
Please test again... i'm not able to reproduce those bugs

**Comment by zufrieden** [comment]
Problème dans le blog .... sur IE8
http://sht.tl/P5ip

A-t-on chargé ton script dans WP ? @gagarine ?

**Comment by gagarine** [comment]
I check on my IE8 and it works now...
